### ISSUE TITLE
I placed an ImageView in a list item and set its onClickListener and clicking/refreshing get confused

### ISSUE THREAD

**Issue by milkrun** [woozzu/RefreshableListView#3]
Folks,

The RefreshableListView is working great for me in most cases.

However, in one of my lists I have an ImageView where I have set the onClickListener (for revealing details)

When I try to click on the ImageView, the list refreshes instead of letting me click on the details.

Please help,

Thanks

**Comment by pboos** [comment]
Confirmed.

I actually just fixed this and several other bugs ;-). Will send a pull request soon.
Bugs fixed:
- setting onClickListener in a child view confuses stuff
- setOnItemClickListener is called with wrong positions (because of header view position is always +1)
- bug in 2.2 emulator (and my 2.2 phones)
